/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.BinaryExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link com.shark.lang.dd.BinaryExpression#getOp <em>Op</em>}</li>
 *   <li>{@link com.shark.lang.dd.BinaryExpression#getRight <em>Right</em>}</li>
 *   <li>{@link com.shark.lang.dd.BinaryExpression#getValue <em>Value</em>}</li>
 *   <li>{@link com.shark.lang.dd.BinaryExpression#getPrecision <em>Precision</em>}</li>
 *   <li>{@link com.shark.lang.dd.BinaryExpression#getLength <em>Length</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getBinaryExpression()
 * @model
 * @generated
 */
public interface BinaryExpression extends SharkExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(SharkExpression)
   * @see com.shark.lang.dd.DdPackage#getBinaryExpression_Left()
   * @model containment="true"
   * @generated
   */
  SharkExpression getLeft();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.BinaryExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(SharkExpression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * The literals are from the enumeration {@link com.shark.lang.dd.BinaryOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see com.shark.lang.dd.BinaryOperator
   * @see #setOp(BinaryOperator)
   * @see com.shark.lang.dd.DdPackage#getBinaryExpression_Op()
   * @model
   * @generated
   */
  BinaryOperator getOp();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.BinaryExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see com.shark.lang.dd.BinaryOperator
   * @see #getOp()
   * @generated
   */
  void setOp(BinaryOperator value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(SharkExpression)
   * @see com.shark.lang.dd.DdPackage#getBinaryExpression_Right()
   * @model containment="true"
   * @generated
   */
  SharkExpression getRight();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.BinaryExpression#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(SharkExpression value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see com.shark.lang.dd.DdPackage#getBinaryExpression_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.BinaryExpression#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Precision</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precision</em>' attribute.
   * @see #setPrecision(int)
   * @see com.shark.lang.dd.DdPackage#getBinaryExpression_Precision()
   * @model
   * @generated
   */
  int getPrecision();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.BinaryExpression#getPrecision <em>Precision</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precision</em>' attribute.
   * @see #getPrecision()
   * @generated
   */
  void setPrecision(int value);

  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see com.shark.lang.dd.DdPackage#getBinaryExpression_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.BinaryExpression#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

} // BinaryExpression
