/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.ListExpression#getOp <em>Op</em>}</li>
 *   <li>{@link com.shark.lang.dd.ListExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link com.shark.lang.dd.ListExpression#getListElts <em>List Elts</em>}</li>
 *   <li>{@link com.shark.lang.dd.ListExpression#getRange <em>Range</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getListExpression()
 * @model
 * @generated
 */
public interface ListExpression extends SharkExpression
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see com.shark.lang.dd.DdPackage#getListExpression_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.ListExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(SharkExpression)
   * @see com.shark.lang.dd.DdPackage#getListExpression_Left()
   * @model containment="true"
   * @generated
   */
  SharkExpression getLeft();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.ListExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(SharkExpression value);

  /**
   * Returns the value of the '<em><b>List Elts</b></em>' containment reference list.
   * The list contents are of type {@link com.shark.lang.dd.ListExpressionElt}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Elts</em>' containment reference list.
   * @see com.shark.lang.dd.DdPackage#getListExpression_ListElts()
   * @model containment="true"
   * @generated
   */
  EList<ListExpressionElt> getListElts();

  /**
   * Returns the value of the '<em><b>Range</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' attribute.
   * @see #setRange(String)
   * @see com.shark.lang.dd.DdPackage#getListExpression_Range()
   * @model
   * @generated
   */
  String getRange();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.ListExpression#getRange <em>Range</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' attribute.
   * @see #getRange()
   * @generated
   */
  void setRange(String value);

} // ListExpression
