/**
 * generated by Xtext 2.23.0
 */
package com.shark.lang.dd;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#getOp <em>Op</em>}</li>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#getValue <em>Value</em>}</li>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#getPrecision <em>Precision</em>}</li>
 *   <li>{@link com.shark.lang.dd.UnaryExpression#getLength <em>Length</em>}</li>
 * </ul>
 *
 * @see com.shark.lang.dd.DdPackage#getUnaryExpression()
 * @model
 * @generated
 */
public interface UnaryExpression extends SharkExpression
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * The literals are from the enumeration {@link com.shark.lang.dd.UnaryOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see com.shark.lang.dd.UnaryOperator
   * @see #setOp(UnaryOperator)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_Op()
   * @model
   * @generated
   */
  UnaryOperator getOp();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see com.shark.lang.dd.UnaryOperator
   * @see #getOp()
   * @generated
   */
  void setOp(UnaryOperator value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(SharkExpression)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_Left()
   * @model containment="true"
   * @generated
   */
  SharkExpression getLeft();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(SharkExpression value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Precision</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Precision</em>' attribute.
   * @see #setPrecision(int)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_Precision()
   * @model
   * @generated
   */
  int getPrecision();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#getPrecision <em>Precision</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Precision</em>' attribute.
   * @see #getPrecision()
   * @generated
   */
  void setPrecision(int value);

  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see com.shark.lang.dd.DdPackage#getUnaryExpression_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link com.shark.lang.dd.UnaryExpression#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

} // UnaryExpression
